# Generated by Django 4.2.1 on 2024-09-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_section_is_solved_section_score_alter_course_modules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="section",
            name="is_solved",
        ),
        migrations.RemoveField(
            model_name="section",
            name="score",
        ),
    ]
