# Generated by Django 4.2.1 on 2024-09-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_sectionsolve"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sectionsolve",
            name="is_solved",
        ),
        migrations.AddField(
            model_name="sectionsolve",
            name="solve_status",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
