# Generated by Django 4.2.1 on 2024-09-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_remove_sectionsolve_is_solved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonsection",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="courses.lesson",
            ),
        ),
    ]
