# Generated by Django 4.2.1 on 2024-09-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_lessonsection_lesson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="section",
            field=models.ManyToManyField(
                blank=True,
                related_name="lessons",
                through="courses.LessonSection",
                to="courses.section",
            ),
        ),
        migrations.AlterField(
            model_name="lessonsection",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="courses.lesson"
            ),
        ),
    ]
