# Generated by Django 4.2.1 on 2024-09-03 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tasksolutions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tasks.author"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tasks.difficultylevel"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tasks.tasksource"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tasks.tasktopic"
            ),
        ),
    ]
