# Generated by Django 4.2.1 on 2024-10-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskexam_task_exam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tasks.taskexam"
            ),
        ),
    ]
